import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Breadcrumbs from "../components/ui/Breadcrumbs";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Gabriel Skog's Personal Site",
  description: "Generated by create next app",
  other: {
    "google-site-verification": "ShYniVU_EPSEz_HAIQoDC8HU5tc2wro2XTJtuklUJw4"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Breadcrumbs /> {/* 👈 placeras här */}
        {children}
      </body>
    </html>
  );
}
